name: Update Leaderboard

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas numpy scikit-learn

      - name: Run evaluation
        run: python evaluate.py

      - name: Update CSV
        run: |
          name=$(jq -r '.name' result.json)
          acc=$(jq -r '.accuracy' result.json)
          f1=$(jq -r '.f1' result.json)

          # Remove header + remove existing user
          tail -n +2 leaderboard.csv | grep -v "^$name," > temp.csv || true

          # Add updated row
          echo "$name,$acc,$f1" >> temp.csv

          # Write fresh CSV with single header
          echo "Name,Accuracy,F1" > leaderboard.csv
          cat temp.csv >> leaderboard.csv

          rm temp.csv

      - name: Commit changes
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"

          git add leaderboard.csv
          git commit -m "update leaderboard" || echo "No changes"
          git push
